export const BUTTON_ACTIONS = {
  "number-0": 0,
  "number-1": 1,
  "number-2": 2,
  "number-3": 3,
  "number-4": 4,
  "number-5": 5,
  "number-6": 6,
  "number-7": 7,
  "number-8": 8,
  "number-9": 9,
  addition: "+",
  subtraction: "-",
  multiplication: "*",
  division: "/",
  equals: "=",
  decimal: ".",
  modulo: "%",
};
